---
title: "Introduction to the SataEasyPlot R Package"
author: "XueyuGuo"
date: "`r Sys.Date()`"
output: 
  #rmarkdown::html_vignette
  prettydoc::html_pretty:
    theme: hpstr
	highlight: github
	toc: true
	mathjax: null
	self_contained: true
	  prettydoc::html_pretty:
	    theme: hpstr
		highlight: github
		toc: true
		mathjax: null
		self_contained: true
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options:
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
  chunk_output_type: console
)
```

```{r setup}
library(StatEasyPlot)
```

## Overview
StatEasyPlot uses [ggplot2] [ggrepel] and [ggsci] to make plots:
- `line_plot()`
- `lines_plot()`
- `histogram_plot()`
- `oneline_histogram_plot()`
- `sv_count()`

[ggplot2]: http://ggplot2.tidyverse.org/


## Installation
The [latest development version][github] may have new features, and you can get
it from GitHub:
```{r install-github, echo=TRUE, eval=FALSE}
# Use the devtools package
# install.packages("devtools")
devtools::install_github("guoxueyu/StatEasyPlot")
```

[github]: https://github.com/guoxueyu/StatEasyPlot

## Usage
See the [examples] page to learn more about how to use ggrepel in your project.

